services:
  - type: web
    name: my-spring-app
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -Dserver.port=$PORT -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17